[soc]
core = ["c0","c0"]
[c0]
type  = "ooo"
caches        = true
scb_size      = 16
dl1           = "dl1_cache DL1"
il1           = "dl1_cache IL1"
[dl1_cache]
type       = "cache"
cold_misses = true
size       = 32768
line_size  = 64
delay      = 5
miss_delay = 2
assoc      = 4
repl_policy = "lru"
port_occ   = 1
port_num   = 1
port_banks = 32
send_port_occ = 1
send_port_num = 1
max_requests  = 32
allocate_miss = true
victim        = false
coherent      = true
inclusive     = true
directory     = false
nlp_distance = 2
nlp_degree   = 1       # 0 disabled
nlp_stride   = 1
drop_prefetch = true
prefetch_degree = 0    # 0 disabled
mega_lines1K    = 8    # 8 lines touched, triggers mega/carped prefetch
lower_level = "privl2 L2 sharedby 2"
